# Generated by Django 5.0 on 2023-12-20 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
