# Generated by Django 5.0 on 2023-12-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0004_alter_customuser_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
