# Generated by Django 4.2.6 on 2023-11-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
